##ASSIGNMENT 1 - DATA STRUCTURES

1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True,8.10.

a. Now in the ‘myList’, append these values: 30,40

b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [1]:
# create the list 'myList' with the given elements
myList = [10, 20, 30, 'apple', True, 8.10]

# append 30 and 40 to 'myList'
myList.append(30)
myList.append(40)

# reverse the elements of 'myList' and store it in 'reversedList'
reversedList = myList[::-1]

# print both the lists
print("Original List:", myList)
print("Reversed List:", reversedList)

Original List: [10, 20, 30, 'apple', True, 8.1, 30, 40]
Reversed List: [40, 30, 8.1, True, 'apple', 30, 20, 10]


2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.

a. After that eliminate the ‘text’ value form the dictonary.

b. Add ‘features’ in the dictonary.

c. Fetch the ‘data’ element from the dictonary and display it in the output.

In [2]:
# create the dictionary with keys 1, 2, and 3, and values 'data', 'information', and 'text'
myDict = {1: 'data', 2: 'information', 3: 'text'}

# remove the 'text' value from the dictionary
del myDict[3]

# add 'features' to the dictionary
myDict[4] = 'features'

# fetch the 'data' element from the dictionary and display it in the output
print("The 'data' element from the dictionary is:", myDict[1])

The 'data' element from the dictionary is: data


3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [3]:
# create a tuple named 'my_tuple' and add the elements 1, 2, 3, 'apple', and 'mango' to it
my_tuple = (1, 2, 3, 'apple', 'mango')

# print the tuple
print(my_tuple)


(1, 2, 3, 'apple', 'mango')


4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50

a. Find the minimum value from the numeric_tuple.

b. Concatenate my_tuple with numeric_tuple and store the result in r1.

c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [4]:
# create a tuple named 'numeric_tuple' consisting of integer values 10, 20, 30, 40, and 50
numeric_tuple = (10, 20, 30, 40, 50)

# find the minimum value from 'numeric_tuple'
min_value = min(numeric_tuple)

# concatenate 'my_tuple' with 'numeric_tuple' and store the result in a new tuple named 'r1'
r1 = my_tuple + numeric_tuple

# duplicate 'my_tuple' two times and store it in a new tuple named 'newdupli'
newdupli = my_tuple * 2

# print the minimum value, 'r1', and 'newdupli'
print("The minimum value from 'numeric_tuple' is:", min_value)
print("The concatenated tuple of 'my_tuple' and 'numeric_tuple' is:", r1)
print("The duplicated tuple of 'my_tuple' is:", newdupli)

The minimum value from 'numeric_tuple' is: 10
The concatenated tuple of 'my_tuple' and 'numeric_tuple' is: (1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)
The duplicated tuple of 'my_tuple' is: (1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to contains{2,3,7,6,1}

a. Perform the below operation:

B. set1 union set2

C. set1 intersection set2

D. set1 difference set2

In [5]:
# create two sets named 'set1' and 'set2'
set1 = {1, 2, 3, 4, 5}
set2 = {2, 3, 7, 6, 1}

# perform set union of 'set1' and 'set2'
union_set = set1.union(set2)
print("The union of 'set1' and 'set2' is:", union_set)

# perform set intersection of 'set1' and 'set2'
intersection_set = set1.intersection(set2)
print("The intersection of 'set1' and 'set2' is:", intersection_set)

# perform set difference of 'set1' and 'set2'
difference_set = set1.difference(set2)
print("The difference of 'set1' and 'set2' is:", difference_set)

The union of 'set1' and 'set2' is: {1, 2, 3, 4, 5, 6, 7}
The intersection of 'set1' and 'set2' is: {1, 2, 3}
The difference of 'set1' and 'set2' is: {4, 5}


##ASSIGNMENT 2 - NUMPY

1. Create a 3x3 matrix array with values ranging from 2 to 10

In [6]:
import numpy as np

arr = np.arange(2, 11).reshape(3, 3)
print(arr)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [10]:
# create an empty list to store user input values
values = []

# take user input for the values and append them to the list
while True:
    value = input("Enter a value (or 'done' to stop): ")
    if value == 'done':
        break
    values.append(int(value))

# create a NumPy array from the list of values
arr = np.array(values)

# convert the integer type to the float type of the elements
arr = arr.astype('float')

# print the original and converted arrays
print("Original array:", values)
print("Array converted to a float type:", arr)

Enter a value (or 'done' to stop): 2
Enter a value (or 'done' to stop): 3
Enter a value (or 'done' to stop): 1
Enter a value (or 'done' to stop): 5
Enter a value (or 'done' to stop): done
Original array: [2, 3, 1, 5]
Array converted to a float type: [2. 3. 1. 5.]


3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [11]:
# create the original array
arr = np.array([10, 20, 30])

# append values to the end of the array
arr = np.append(arr, [40, 50, 60, 70, 80, 90])

# print the updated array
print(arr)

[10 20 30 40 50 60 70 80 90]


4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [12]:
# create the first array
arr1 = np.array([1, 2, 3])

# create the second array
arr2 = np.array([4, 5, 6])

# add the elements of both arrays and store the result in sumArray
sumArray = arr1 + arr2

# print the sumArray
print(sumArray)


[5 7 9]


5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform
the following tasks:

a. Extract the 1st row from the array.

b. Extract the last element from the array.

In [14]:
# create the array1 with values from 10-90 with interval of 10
array1 = np.arange(10, 100, 10).reshape(3, 3)

# extract the first row from the array
row1 = array1[0]

# extract the last element from the array
last_elem = array1[-1][-1]

# print the first row and the last element
print("First row:", row1)
print("Last element:", last_elem)

First row: [10 20 30]
Last element: 90


## CASE STUDY PROBLEM 1


1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]

In [15]:
def solve(dimensions, value):
    return np.full(dimensions, value)

In [16]:
# call the solve function with dimensions (3, 3) and value 5
result = solve((3, 3), 5)

# print the result
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [17]:
def sum_arrays(*arrays):
    return np.sum(arrays, axis=0)


In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])

result = sum_arrays(a, b, c)
print(result) 

[[15 18]
 [21 24]]


3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]

In [19]:
def top_left_sub_matrix(matrix, N, M):
    return matrix[:N, :M]

4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]

In [20]:
def sub_matrix(matrix, n, m):
    rows, cols = matrix.shape
    return matrix[rows-n:, cols-m:]

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix(matrix, 1, 1)

array([[9]])

5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}

In [22]:
def get_mean_std(arr):
    return {'mean': np.mean(arr), 'std_dev': np.std(arr)}

In [23]:
arr = np.array([1, 1, 1])
result = get_mean_std(arr)
print(result) 

{'mean': 1.0, 'std_dev': 0.0}
